### PR TITLE
using inventory batch API with queue buffering and diagnostics

### PR DESCRIPTION
**Pull request by jmazzitelli**
this incorporates but also replaces PR #73 - see commit messages for details

### CODE REVIEW

**Comment by ppalaga** [comment]
... and I was hoping to silently get rid of those useless multiline diagnostic messages in the log ;)

**Comment by jmazzitelli** [comment]
Hardly useless! Very helpful in diagnosing performance! Take a closer look at the information in them. BTW: those diagnostic metrics can actually be stored in hawkular-metrics itself rather than in the server log (so the agent can store its own metrics in h-metrics) by changing "LOG" to "STORAGE" in the <diagnostics> configuration in standalone.xml.

**Comment by jmazzitelli** [comment]
Oh, and you can also change the interval at which those diagnostic logs are emitted - again, configurable in <diagnostics> element in standalone.xml. Right now I believe it is set at 1 minute, but you can set it to anything (5 minutes, 60 minutes, whatever)

**Comment by ppalaga** [comment]
Configurable? - Great! I'll set it to max in my env not to see it ;)

**Comment by jmazzitelli** [comment]
You can set it to 1,000,000 minutes if you never want to see it :)

**Pull request merged**
