### PR TITLE
Replace srcdeps-maven-plugin with srcdeps core extension

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jmazzitelli could you please review?

https://travis-ci.org/hawkular/hawkular-agent/builds/179816760#L9260 is actually a success, is it not? IT has frozen only after `BUILD SUCCESS` which is IMO enough, to call it success.

**Comment by ppalaga** [comment]
@jmazzitelli the CI passed on the second attempt. Is this good to merge?

**Comment by jmazzitelli** [comment]
I was waiting for the other project leads to merge their PRs and to tell me that this is OK. Has the other hawkular projects given the OK and merged mvnw into their master branches?

**Comment by jshaughn** [comment]
Alerting merged it in and I have not seen any issues, nor have I had to change anything I've been doing when building.

**Comment by ppalaga** [comment]
> Has the other hawkular projects given the OK and merged mvnw into their master branches?

Yes, most of them are merged:

* https://github.com/hawkular/hawkular-parent-pom/pull/93
* https://github.com/hawkular/hawkular-commons/pull/92
* https://github.com/hawkular/hawkular-inventory/pull/319
* https://github.com/hawkular/hawkular-apm/pull/694
* https://github.com/hawkular/hawkular-metrics/pull/704

Only the present one and https://github.com/hawkular/hawkular-services/pull/104 are still open.

**Pull request merged**
