### PR TITLE
HAWKULAR-1005 catch errors and send err msg back

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jpkrohling** [comment]
LGTM, as long as the failures are expected :)

**Comment by ppalaga** [comment]
I vote for squashing the two commits together and making the commit messages start with a capital letter. Othewise, LGTM.

**Comment by jmazzitelli** [comment]
Failures are not expected :)

**Comment by jmazzitelli** [comment]
Looks like a local travis error:
Failed to execute goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.1.2.Final:build (server-provisioning) on project hawkular-wildfly-agent-wf-extension: Execution server-provisioning of goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.1.2.Final:build failed: java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file -> [Help 1]

I have no idea what its saying. but that doesn't happen locally.

**Pull request merged**
