### PR TITLE
HAWKULAR-454 the context for hawkular accounts changed in accounts 1.0.12.Final

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by ppalaga** [comment]
Waiting for Accounts 1.0.12.Final

**Comment by jpkrohling** [comment]
Accounts 1.0.12.Final is released.

**Comment by jmazzitelli** [comment]
accounts 1.0.12.Final has been released with the new path. we can merge this when ready

**Comment by ppalaga** [comment]
Replaced by 5fa5ba7 via https://github.com/hawkular/hawkular-agent/pull/45

**Pull request closed without merging**
