### PR TITLE
Upgrade to inventory 0.19.x.Final.

### PR DESCRIPTION
**Pull request by metlos**
This require updates to how integration tests are run, because inventory
now needs datasources defined in the server.

This should enable you to go async again...

### CODE REVIEW

**Comment by metlos** [comment]
Huh, so seeing the tests on Travis passing for commit 1b15409 and NOT passing for e31d4f1 I wonder if the failures are environmental? The difference between inv `0.19.0.Final` and `0.19.1.Final` are JUST in the way they're built. The relevant code is completely identical.

**Comment by metlos** [comment]
@jmazzitelli, could you please try restarting those tests on Travis to see if this fails again?

**Comment by pilhuhn** [comment]
On 20 Sep 2016, at 13:55, Lukas Krejci wrote:

> @jmazzitelli, could you please try restarting those tests on Travis to 
> see if this fails again?

I restarted it.

**Comment by jshaughn** [comment]
Note, @metlos, I had restarted it once before and it had failed, I believe, at the same place twice.  We'll see how this one goes...

**Comment by jmazzitelli** [comment]
This seems to be failing consistently in the same place - at least, the past two times.

**Comment by jmazzitelli** [comment]
we need to find out why travis is failing here. It did it again, in the exact same spot. Something is wrong. And I suspect it travis-specific, but I am not sure.

**Comment by metlos** [comment]
I've created another pr to try and get this past Travis. It has an exceptionally nice round number #256 :smile:

**Comment by pilhuhn** [comment]
What is the status of this one @metlos ?

**Comment by metlos** [comment]
I gave up on this...

**Comment by jmazzitelli** [comment]
we got it to go green on inventory 1.0.0.Final in another PR. closing this

**Pull request closed without merging**
