### PR TITLE
HWKAGENT-133 platform resource types and their metrics should have more unique IDs

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by jshaughn** [comment]
This is probably OK but before releasing (or maybe merging) it may be worthwhile to post changes like this on dev-list, just to make sure there is no downstream downstream impact in the provider code.

**Comment by jmazzitelli** [comment]
already in the process of writing the email

**Comment by jmazzitelli** [comment]
> > post changes like this on dev-list
> 
> already in the process of writing the email

http://lists.jboss.org/pipermail/hawkular-dev/2016-August/003176.html

**Comment by jshaughn** [comment]
A quick github search didn't reveal any hits for the old names, except in miq for some other providers... LGTM.

**Pull request merged**
