### PR TITLE
HWKAGENT-149 websocket reconnect

### PR DESCRIPTION
**Pull request by jmazzitelli**
I haven't been able to replicate, but I think this could solve the problem

### CODE REVIEW

**Comment by jmazzitelli** [comment]
Do not merge this yet. Going to try to also add a ping-pong so we have traffic going over the websocket continuously, which should hopefully avoid the websocket getting mysteriously shutdown due to inactivity.

**Comment by jmazzitelli** [comment]
@pilhuhn if possible, try this out. I have not yet been able to figure out a way to test it for the use-case you found (where onFailure is called but onClose is not). Not trivial to set this up in our itest infrastructure. But I think this should fix it. I also added a WebSocket ping so that should keep the connection from getting killed due to the connection being quiet (it isn't quiet anymore with the periodic pings).

**Comment by pilhuhn** [comment]
It seems to do something now. When I kill the server I get 

```
09:23:21,609 WARN  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010036: Feed communications channel encountered a failure. Response=[<null>]: java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

09:23:21,612 WARN  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010038: Failed to close web socket with code=[1000] and reason=[Shutting down FeedCommProcessor]: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at okio.Okio$1.write(Okio.java:80)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.emit(RealBufferedSink.java:183)
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
	at com.squareup.okhttp.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
	at org.hawkular.agent.monitor.cmd.FeedCommProcessor.disconnect(FeedCommProcessor.java:151)
	at org.hawkular.agent.monitor.cmd.FeedCommProcessor.onFailure(FeedCommProcessor.java:337)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readerErrorClose(RealWebSocket.java:217)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:100)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

and after a while I see

```
09:24:28,860 WARN  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010036: Feed communications channel encountered a failure. Response=[<null>]: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:573)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.access$100(Call.java:35)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

and other warnings up to finally:

`09:24:56,619 INFO  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010034: Opened feed WebSocket connection to endpoint [ws://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf]`

**Comment by pilhuhn** [comment]
Later I got
```
09:31:36,465 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,466 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,466 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,466 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,466 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,467 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,475 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,475 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,475 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,475 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,475 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,475 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,480 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,480 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,480 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,480 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
09:31:36,480 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?

```

**Comment by pilhuhn** [comment]
Now when I tcpkill the websocket connection I see

```
09:47:30,459 WARN  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010036: Feed communications channel encountered a failure. Response=[<null>]: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
	at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

09:47:30,461 WARN  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010038: Failed to close web socket with code=[1000] and reason=[Shutting down FeedCommProcessor]: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at okio.Okio$1.write(Okio.java:80)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.emit(RealBufferedSink.java:183)
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
	at com.squareup.okhttp.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
	at org.hawkular.agent.monitor.cmd.FeedCommProcessor.disconnect(FeedCommProcessor.java:151)
	at org.hawkular.agent.monitor.cmd.FeedCommProcessor.onFailure(FeedCommProcessor.java:337)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readerErrorClose(RealWebSocket.java:217)
	at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:100)
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

09:47:31,473 INFO  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010034: Opened feed WebSocket connection to endpoint [ws://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf]

```

**Comment by jmazzitelli** [comment]
Everything looks good except for:

````
09:31:36,465 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to http://snert:8080/ was leaked. Did you forget to close a response body?
````

I need to find out where I don't close this. I thought I got them all?

**Comment by jmazzitelli** [comment]
I don't know if what I just "fixed" will correct the problem with the leaked connection warnings, but I noticed that the sendPing javadoc says close must be called on IOException, which the code was not doing before. It does this now. Again, I don't know if this really will fix that leak, but it needed to get done anyway, as per the okhttp javadoc.

@pilhuhn what's the replication procedures you followed to get those warnings? Start h-server, start h-agent, and ?? kill the server? or leave the server up but just somehow use tcpkill? What's the actual cmd line you used to kill the connection?

**Comment by pilhuhn** [comment]
@jmazzitelli With the leaked connections I have a running server, make the agent connect to it and afte a while stop the server. Agent is trying to re-connect for a while. Then I start the server again. Agent re-connects. And after a while I see the warnings. I haven't counted if it is always the same number or if that varies with the time the server was not reachable (or took to start up).

**Comment by pilhuhn** [comment]
@jmazzitelli The number of warnings seems to correlate with the number of times this warning was printed:

```
09:31:47,773 WARN  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf) HAWKMONITOR010036: Feed communications channel encountered a failure. Response=[Response{protocol=http/1.1, code=404, message=Not Found, url=http://snert:8080/hawkular/command-gateway/feed/c256ae3f-383a-4197-9d27-fe1d880452cf}]: java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:123)
	at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
	at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jmazzitelli** [comment]
> @jmazzitelli The number of warnings seems to correlate with the number of times this warning was printed:

This is odd because the warning says, "Did you forget to close a response body?" but in the code where I think this is coming from, I do close the response body:

```
  log.warnFeedCommFailure(response.toString(), e);
  if (response.body() != null) {
      try {
          response.body().close();
      } catch (Exception ignore) {
      }
  }
```

I'm gonna keep trying to figure out if I really am leaking something (I guess I am, otherwise that warning wouldn't come out).

**Comment by jmazzitelli** [comment]
Interestingly, this class never closed the response in the onOpen method. That's the one place where I see a reponse object not getting its body closed. I think that is probably the issue.

**Comment by jmazzitelli** [comment]
Even after adding the code to close the response body in onOpen, I just got those warnings myself. And yes I got the same amount of warnings as I did errors like this one:

````
15:20:12,948 WARN  [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://localhost.localdomain:8080/hawkular/command-gateway/feed/b964f327-f0eb-466b-b686-9e436cf43062)
HAWKMONITOR010036: Feed communications channel encountered a failure. Response=[Response{protocol=http/1.1, code=404, message=Not Found, 
url=http://localhost.localdomain:8080/hawkular/command-gateway/feed/b964f327-f0eb-466b-b686-9e436cf43062}]: java.net.ProtocolException:
Expected HTTP 101 response but was '404 Not Found'
````

But the code where that warning is logged is also the code where I also close the response body. I have a feeling it might be an internal issue with okhttp because there is no other place in the code where the response body isn't being closed. Unless there is some other cause of that warning.

**Comment by jmazzitelli** [comment]
I cannot get this to repeatedly happen. I tried two more times and never saw that warning

**Comment by jmazzitelli** [comment]
spoke too soon, I saw it again. I think it has to do with the new pinging.

**Comment by jmazzitelli** [comment]
I think its a problem in okhttp - I can't find any other place where I'm NOT calling close on the response body. This guy (who didn't get an answer) says he sees the same thing: http://stackoverflow.com/questions/38380371/okhttp-avoid-leaked-connection-warning

**Comment by jmazzitelli** [comment]
I'm going to merge this. I think this "leak" only happens when the server is down, and it doesn't happen all the time (I only see it rarely - most times, I don't see it).

**Pull request merged**
