### PR TITLE
Updated to Accounts 1.1.1.Final

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Will re-submit with new version.

**Comment by pilhuhn** [comment]
@jpkrohling Is that still relevant? Especially given that accounts is at 2.0.6+ now

**Comment by jpkrohling** [comment]
The 2.x branch is for WF 10, so, if there's a subsequent commit here that is needed in the main Hawkular, it would need to wait for WF 10 to arrive there before consuming this new version of the agent. 

So, 1.x is still appropriate.

**Comment by jpkrohling** [comment]
By the way, it seems this has already somehow arrived at master. So, this can be closed.

**Pull request closed without merging**
