### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by jmazzitelli**
trying to fix these tests. we need to figure out if we really do not want to persist metric types (on resource types). there is no metric type, just metric on resource - unsure if what is really what we want.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
The unit tests pass now. This can be merged after review.

**Comment by jmazzitelli** [comment]
@jotak you might want to look this over. Nothing major, just make sure it isn't completely wrong.

**Review by jotak — APPROVED** [review]

**Comment by jotak** [comment]
I don't have the rights for merge, but +1
@lucasponce can you merge?

**Comment by lucasponce** [comment]
@jotak I am afraid I have a free subscripcion on this repo and I don't have rights to merge either.

**Pull request merged**
