### PR TITLE
HWKAGENT-86 Remove Accounts

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jmazzitelli @jpkrohling let's see what Travis will say. I am seeing the NameNodFoundException thrown when metrics is being deployed quite often now:

```
    Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
java.lang.IllegalArgumentException: WFLYWELD0049: Error injecting resource into CDI managed bean. Can't find a resource named java:/topic/HawkularAvailData defined on private javax.jms.Topic org.hawkular.metrics.component.publish.InsertedDataSubscriber.availabilityTopic
    at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices.resolveResource(WeldResourceInjectionServices.java:216)
    at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices$1.createResource(WeldResourceInjectionServices.java:162)
    at org.jboss.weld.injection.AbstractResourceInjection.getResourceReference(AbstractResourceInjection.java:49)
    at org.jboss.weld.injection.AbstractResourceInjection.injectResourceReference(AbstractResourceInjection.java:63)
    at org.jboss.weld.util.Beans.injectEEFields(Beans.java:351)
    at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
    at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
    at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:72)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:121)
    at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:159)
    at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
    at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
    at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
    at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
    at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
    at org.hawkular.metrics.component.publish.InsertedDataSubscriber$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
    at org.hawkular.metrics.api.jaxrs.util.EagerExtension.load(EagerExtension.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
    at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:309)
    at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
    at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:287)
    at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:265)
    at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
    at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
    at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
    at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
    at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
    at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
    at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
    at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:450)
    at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
    at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:96)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.naming.NameNotFoundException: topic/HawkularAvailData [Root exception is java.lang.IllegalStateException]
    at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:153)
    at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:83)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:207)
    at org.jboss.as.naming.InitialContext$DefaultInitialContext.lookup(InitialContext.java:235)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:193)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:189)
    at javax.naming.InitialContext.lookup(InitialContext.java:417)
    at javax.naming.InitialContext.lookup(InitialContext.java:417)
    at org.jboss.as.weld.services.bootstrap.WeldResourceInjectionServices.resolveResource(WeldResourceInjectionServices.java:214)
    ... 42 more
Caused by: java.lang.IllegalStateException
    at org.jboss.msc.value.InjectedValue.getValue(InjectedValue.java:47)
    at org.jboss.as.naming.service.BinderService.getValue(BinderService.java:138)
    at org.jboss.as.naming.service.BinderService.getValue(BinderService.java:46)
    at org.jboss.msc.service.ServiceControllerImpl.getValue(ServiceControllerImpl.java:1158)
    at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:131)
    ... 50 more
"}}
```

**Comment by ppalaga** [comment]
Timeouts on both ends of the WebSocket... the docker node seems to be overloaded: 

```
20:43:41,531 TRACE [org.hawkular.agent.monitor.cmd.FeedCommProcessor] (OkHttp http://localhost:8080/hawkular/command-gateway/feed/d397fd11-eb2f-48b8-8cd8-aa858c476b22) Feed communications had a failure - a reconnection is likely required: java.net.SocketTimeoutException: timeout
114723 [OkHttp http://localhost:8080/hawkular/command-gateway/feed/d397fd11-eb2f-48b8-8cd8-aa858c476b22] TRACE org.hawkular.agent.monitor.cmd.FeedCommProcessor  - Feed communications had a failure - a reconnection is likely required: java.net.SocketTimeoutException: timeout
```

https://travis-ci.org/hawkular/hawkular-agent/builds/131241933#L5661

**Comment by ppalaga** [comment]
2ddf21b is an attempt to solve the build problems on Travis by using a test node type with more RAM

**Comment by ppalaga** [comment]
ed4f610 fixes 2ddf21b

**Comment by ppalaga** [comment]
f205ef0 is yet another fix of the new Travis setup

**Comment by ppalaga** [comment]
4371638 more of the same

**Comment by ppalaga** [comment]
deac4c3 passed, but let's have a look if will pass on a docker node now.

**Comment by ppalaga** [comment]
26497b7 removed the commit 6766fee that switched to non-docker node

**Comment by jmazzitelli** [comment]
@ppalaga  can we rename the title of this PR since it encompasses more than just upgrading okhttp. Just would like a more descriptive name.

**Comment by ppalaga** [comment]
> can we rename the title of this PR since it encompasses more than just upgrading okhttp. Just would like a more descriptive name.

No problem. I hope "HWKAGENT-86 Remove Accounts" is good enough.

**Comment by ppalaga** [comment]
@jmazzitelli 3513bab is good to merge from my side once the CI passes

**Pull request merged**
